/* tslint:disable */
/* eslint-disable */
/**
 * standard public schema
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 12.0.2 (a4e00ff)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { RpcGenSaltPostRequest } from "../models/index";
import {
	RpcGenSaltPostRequestFromJSON,
	RpcGenSaltPostRequestToJSON,
} from "../models/index";
import * as runtime from "../runtime";

export interface RpcDearmorGetRequest {
	test: string;
}

export interface RpcDearmorPostRequest {
	args: RpcGenSaltPostRequest;
	prefer?: RpcDearmorPostPreferEnum;
}

/**
 *
 */
export class RpcDearmorApi extends runtime.BaseAPI {
	/**
	 */
	async rpcDearmorGetRaw(
		requestParameters: RpcDearmorGetRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<runtime.ApiResponse<void>> {
		if (requestParameters[""] == null) {
			throw new runtime.RequiredError(
				"",
				'Required parameter "" was null or undefined when calling rpcDearmorGet().',
			);
		}

		const queryParameters: any = {};

		if (requestParameters[""] != null) {
			queryParameters[""] = requestParameters[""];
		}

		const headerParameters: runtime.HTTPHeaders = {};

		let urlPath = `/rpc/dearmor`;

		const response = await this.request(
			{
				path: urlPath,
				method: "GET",
				headers: headerParameters,
				query: queryParameters,
			},
			initOverrides,
		);

		return new runtime.VoidApiResponse(response);
	}

	/**
	 */
	async rpcDearmorGet(
		requestParameters: RpcDearmorGetRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<void> {
		await this.rpcDearmorGetRaw(requestParameters, initOverrides);
	}

	/**
	 */
	async rpcDearmorPostRaw(
		requestParameters: RpcDearmorPostRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<runtime.ApiResponse<void>> {
		if (requestParameters["args"] == null) {
			throw new runtime.RequiredError(
				"args",
				'Required parameter "args" was null or undefined when calling rpcDearmorPost().',
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		headerParameters["Content-Type"] = "application/json";

		if (requestParameters["prefer"] != null) {
			headerParameters["Prefer"] = String(requestParameters["prefer"]);
		}

		let urlPath = `/rpc/dearmor`;

		const response = await this.request(
			{
				path: urlPath,
				method: "POST",
				headers: headerParameters,
				query: queryParameters,
				body: RpcGenSaltPostRequestToJSON(requestParameters["args"]),
			},
			initOverrides,
		);

		return new runtime.VoidApiResponse(response);
	}

	/**
	 */
	async rpcDearmorPost(
		requestParameters: RpcDearmorPostRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<void> {
		await this.rpcDearmorPostRaw(requestParameters, initOverrides);
	}
}

/**
 * @export
 */
export const RpcDearmorPostPreferEnum = {
	ParamssingleObject: "params=single-object",
} as const;
export type RpcDearmorPostPreferEnum =
	(typeof RpcDearmorPostPreferEnum)[keyof typeof RpcDearmorPostPreferEnum];
