/* tslint:disable */
/* eslint-disable */
/**
 * standard public schema
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 12.0.2 (a4e00ff)
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { RpcArmorPostRequest } from "../models/index";
import {
	RpcArmorPostRequestFromJSON,
	RpcArmorPostRequestToJSON,
} from "../models/index";
import * as runtime from "../runtime";

export interface RpcPgpKeyIdGetRequest {
	test: string;
}

export interface RpcPgpKeyIdPostRequest {
	args: RpcArmorPostRequest;
	prefer?: RpcPgpKeyIdPostPreferEnum;
}

/**
 *
 */
export class RpcPgpKeyIdApi extends runtime.BaseAPI {
	/**
	 */
	async rpcPgpKeyIdGetRaw(
		requestParameters: RpcPgpKeyIdGetRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<runtime.ApiResponse<void>> {
		if (requestParameters[""] == null) {
			throw new runtime.RequiredError(
				"",
				'Required parameter "" was null or undefined when calling rpcPgpKeyIdGet().',
			);
		}

		const queryParameters: any = {};

		if (requestParameters[""] != null) {
			queryParameters[""] = requestParameters[""];
		}

		const headerParameters: runtime.HTTPHeaders = {};

		let urlPath = `/rpc/pgp_key_id`;

		const response = await this.request(
			{
				path: urlPath,
				method: "GET",
				headers: headerParameters,
				query: queryParameters,
			},
			initOverrides,
		);

		return new runtime.VoidApiResponse(response);
	}

	/**
	 */
	async rpcPgpKeyIdGet(
		requestParameters: RpcPgpKeyIdGetRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<void> {
		await this.rpcPgpKeyIdGetRaw(requestParameters, initOverrides);
	}

	/**
	 */
	async rpcPgpKeyIdPostRaw(
		requestParameters: RpcPgpKeyIdPostRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<runtime.ApiResponse<void>> {
		if (requestParameters["args"] == null) {
			throw new runtime.RequiredError(
				"args",
				'Required parameter "args" was null or undefined when calling rpcPgpKeyIdPost().',
			);
		}

		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		headerParameters["Content-Type"] = "application/json";

		if (requestParameters["prefer"] != null) {
			headerParameters["Prefer"] = String(requestParameters["prefer"]);
		}

		let urlPath = `/rpc/pgp_key_id`;

		const response = await this.request(
			{
				path: urlPath,
				method: "POST",
				headers: headerParameters,
				query: queryParameters,
				body: RpcArmorPostRequestToJSON(requestParameters["args"]),
			},
			initOverrides,
		);

		return new runtime.VoidApiResponse(response);
	}

	/**
	 */
	async rpcPgpKeyIdPost(
		requestParameters: RpcPgpKeyIdPostRequest,
		initOverrides?: RequestInit | runtime.InitOverrideFunction,
	): Promise<void> {
		await this.rpcPgpKeyIdPostRaw(requestParameters, initOverrides);
	}
}

/**
 * @export
 */
export const RpcPgpKeyIdPostPreferEnum = {
	ParamssingleObject: "params=single-object",
} as const;
export type RpcPgpKeyIdPostPreferEnum =
	(typeof RpcPgpKeyIdPostPreferEnum)[keyof typeof RpcPgpKeyIdPostPreferEnum];
