/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo.tanstack-query'
import { Route as DemoTableRouteImport } from './routes/demo.table'
import { Route as DemoClerkRouteImport } from './routes/demo.clerk'
import { Route as ApiDemoTqTodosRouteImport } from './routes/api.demo-tq-todos'
import { Route as ApiDemoNamesRouteImport } from './routes/api.demo-names'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo.start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo.start.api-request'
import { Route as DemoSentryTestingRouteImport } from './routes/demo.sentry.testing'
import { Route as DemoFormAddressRouteImport } from './routes/demo.form.address'
import { Route as AccountAccountIdSandboxRouteImport } from './routes/account.$accountId/sandbox'
import { Route as AccountAccountIdCreateRouteImport } from './routes/account.$accountId/create'
import { Route as AccountAccountIdSettingsRouteRouteImport } from './routes/account.$accountId/settings/route'
import { Route as AccountAccountIdApplicationIdRouteRouteImport } from './routes/account.$accountId/$applicationId/route'
import { Route as AccountAccountIdSettingsPlanRouteImport } from './routes/account.$accountId/settings/plan'
import { Route as AccountAccountIdSettingsNotificationsRouteImport } from './routes/account.$accountId/settings/notifications'
import { Route as AccountAccountIdSettingsMembersRouteImport } from './routes/account.$accountId/settings/members'
import { Route as AccountAccountIdSettingsAccountRouteImport } from './routes/account.$accountId/settings/account'
import { Route as AccountAccountIdApplicationIdServicesRouteImport } from './routes/account.$accountId/$applicationId/services'
import { Route as AccountAccountIdApplicationIdSecurityRouteImport } from './routes/account.$accountId/$applicationId/security'
import { Route as AccountAccountIdApplicationIdLogsRouteImport } from './routes/account.$accountId/$applicationId/logs'
import { Route as AccountAccountIdApplicationIdKeysRouteImport } from './routes/account.$accountId/$applicationId/keys'
import { Route as AccountAccountIdApplicationIdInsightsRouteImport } from './routes/account.$accountId/$applicationId/insights'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoClerkRoute = DemoClerkRouteImport.update({
  id: '/demo/clerk',
  path: '/demo/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDemoTqTodosRoute = ApiDemoTqTodosRouteImport.update({
  id: '/api/demo-tq-todos',
  path: '/api/demo-tq-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDemoNamesRoute = ApiDemoNamesRouteImport.update({
  id: '/api/demo-names',
  path: '/api/demo-names',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoSentryTestingRoute = DemoSentryTestingRouteImport.update({
  id: '/demo/sentry/testing',
  path: '/demo/sentry/testing',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountAccountIdSandboxRoute = AccountAccountIdSandboxRouteImport.update({
  id: '/account/$accountId/sandbox',
  path: '/account/$accountId/sandbox',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountAccountIdCreateRoute = AccountAccountIdCreateRouteImport.update({
  id: '/account/$accountId/create',
  path: '/account/$accountId/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountAccountIdSettingsRouteRoute =
  AccountAccountIdSettingsRouteRouteImport.update({
    id: '/account/$accountId/settings',
    path: '/account/$accountId/settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const AccountAccountIdApplicationIdRouteRoute =
  AccountAccountIdApplicationIdRouteRouteImport.update({
    id: '/account/$accountId/$applicationId',
    path: '/account/$accountId/$applicationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AccountAccountIdSettingsPlanRoute =
  AccountAccountIdSettingsPlanRouteImport.update({
    id: '/plan',
    path: '/plan',
    getParentRoute: () => AccountAccountIdSettingsRouteRoute,
  } as any)
const AccountAccountIdSettingsNotificationsRoute =
  AccountAccountIdSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AccountAccountIdSettingsRouteRoute,
  } as any)
const AccountAccountIdSettingsMembersRoute =
  AccountAccountIdSettingsMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AccountAccountIdSettingsRouteRoute,
  } as any)
const AccountAccountIdSettingsAccountRoute =
  AccountAccountIdSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AccountAccountIdSettingsRouteRoute,
  } as any)
const AccountAccountIdApplicationIdServicesRoute =
  AccountAccountIdApplicationIdServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AccountAccountIdApplicationIdRouteRoute,
  } as any)
const AccountAccountIdApplicationIdSecurityRoute =
  AccountAccountIdApplicationIdSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AccountAccountIdApplicationIdRouteRoute,
  } as any)
const AccountAccountIdApplicationIdLogsRoute =
  AccountAccountIdApplicationIdLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => AccountAccountIdApplicationIdRouteRoute,
  } as any)
const AccountAccountIdApplicationIdKeysRoute =
  AccountAccountIdApplicationIdKeysRouteImport.update({
    id: '/keys',
    path: '/keys',
    getParentRoute: () => AccountAccountIdApplicationIdRouteRoute,
  } as any)
const AccountAccountIdApplicationIdInsightsRoute =
  AccountAccountIdApplicationIdInsightsRouteImport.update({
    id: '/insights',
    path: '/insights',
    getParentRoute: () => AccountAccountIdApplicationIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/demo-names': typeof ApiDemoNamesRoute
  '/api/demo-tq-todos': typeof ApiDemoTqTodosRoute
  '/demo/clerk': typeof DemoClerkRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/account/$accountId/$applicationId': typeof AccountAccountIdApplicationIdRouteRouteWithChildren
  '/account/$accountId/settings': typeof AccountAccountIdSettingsRouteRouteWithChildren
  '/account/$accountId/create': typeof AccountAccountIdCreateRoute
  '/account/$accountId/sandbox': typeof AccountAccountIdSandboxRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/sentry/testing': typeof DemoSentryTestingRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/account/$accountId/$applicationId/insights': typeof AccountAccountIdApplicationIdInsightsRoute
  '/account/$accountId/$applicationId/keys': typeof AccountAccountIdApplicationIdKeysRoute
  '/account/$accountId/$applicationId/logs': typeof AccountAccountIdApplicationIdLogsRoute
  '/account/$accountId/$applicationId/security': typeof AccountAccountIdApplicationIdSecurityRoute
  '/account/$accountId/$applicationId/services': typeof AccountAccountIdApplicationIdServicesRoute
  '/account/$accountId/settings/account': typeof AccountAccountIdSettingsAccountRoute
  '/account/$accountId/settings/members': typeof AccountAccountIdSettingsMembersRoute
  '/account/$accountId/settings/notifications': typeof AccountAccountIdSettingsNotificationsRoute
  '/account/$accountId/settings/plan': typeof AccountAccountIdSettingsPlanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/demo-names': typeof ApiDemoNamesRoute
  '/api/demo-tq-todos': typeof ApiDemoTqTodosRoute
  '/demo/clerk': typeof DemoClerkRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/account/$accountId/$applicationId': typeof AccountAccountIdApplicationIdRouteRouteWithChildren
  '/account/$accountId/settings': typeof AccountAccountIdSettingsRouteRouteWithChildren
  '/account/$accountId/create': typeof AccountAccountIdCreateRoute
  '/account/$accountId/sandbox': typeof AccountAccountIdSandboxRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/sentry/testing': typeof DemoSentryTestingRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/account/$accountId/$applicationId/insights': typeof AccountAccountIdApplicationIdInsightsRoute
  '/account/$accountId/$applicationId/keys': typeof AccountAccountIdApplicationIdKeysRoute
  '/account/$accountId/$applicationId/logs': typeof AccountAccountIdApplicationIdLogsRoute
  '/account/$accountId/$applicationId/security': typeof AccountAccountIdApplicationIdSecurityRoute
  '/account/$accountId/$applicationId/services': typeof AccountAccountIdApplicationIdServicesRoute
  '/account/$accountId/settings/account': typeof AccountAccountIdSettingsAccountRoute
  '/account/$accountId/settings/members': typeof AccountAccountIdSettingsMembersRoute
  '/account/$accountId/settings/notifications': typeof AccountAccountIdSettingsNotificationsRoute
  '/account/$accountId/settings/plan': typeof AccountAccountIdSettingsPlanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/demo-names': typeof ApiDemoNamesRoute
  '/api/demo-tq-todos': typeof ApiDemoTqTodosRoute
  '/demo/clerk': typeof DemoClerkRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/account/$accountId/$applicationId': typeof AccountAccountIdApplicationIdRouteRouteWithChildren
  '/account/$accountId/settings': typeof AccountAccountIdSettingsRouteRouteWithChildren
  '/account/$accountId/create': typeof AccountAccountIdCreateRoute
  '/account/$accountId/sandbox': typeof AccountAccountIdSandboxRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/sentry/testing': typeof DemoSentryTestingRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/account/$accountId/$applicationId/insights': typeof AccountAccountIdApplicationIdInsightsRoute
  '/account/$accountId/$applicationId/keys': typeof AccountAccountIdApplicationIdKeysRoute
  '/account/$accountId/$applicationId/logs': typeof AccountAccountIdApplicationIdLogsRoute
  '/account/$accountId/$applicationId/security': typeof AccountAccountIdApplicationIdSecurityRoute
  '/account/$accountId/$applicationId/services': typeof AccountAccountIdApplicationIdServicesRoute
  '/account/$accountId/settings/account': typeof AccountAccountIdSettingsAccountRoute
  '/account/$accountId/settings/members': typeof AccountAccountIdSettingsMembersRoute
  '/account/$accountId/settings/notifications': typeof AccountAccountIdSettingsNotificationsRoute
  '/account/$accountId/settings/plan': typeof AccountAccountIdSettingsPlanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/demo-names'
    | '/api/demo-tq-todos'
    | '/demo/clerk'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/account/$accountId/$applicationId'
    | '/account/$accountId/settings'
    | '/account/$accountId/create'
    | '/account/$accountId/sandbox'
    | '/demo/form/address'
    | '/demo/sentry/testing'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/account/$accountId/$applicationId/insights'
    | '/account/$accountId/$applicationId/keys'
    | '/account/$accountId/$applicationId/logs'
    | '/account/$accountId/$applicationId/security'
    | '/account/$accountId/$applicationId/services'
    | '/account/$accountId/settings/account'
    | '/account/$accountId/settings/members'
    | '/account/$accountId/settings/notifications'
    | '/account/$accountId/settings/plan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/demo-names'
    | '/api/demo-tq-todos'
    | '/demo/clerk'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/account/$accountId/$applicationId'
    | '/account/$accountId/settings'
    | '/account/$accountId/create'
    | '/account/$accountId/sandbox'
    | '/demo/form/address'
    | '/demo/sentry/testing'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/account/$accountId/$applicationId/insights'
    | '/account/$accountId/$applicationId/keys'
    | '/account/$accountId/$applicationId/logs'
    | '/account/$accountId/$applicationId/security'
    | '/account/$accountId/$applicationId/services'
    | '/account/$accountId/settings/account'
    | '/account/$accountId/settings/members'
    | '/account/$accountId/settings/notifications'
    | '/account/$accountId/settings/plan'
  id:
    | '__root__'
    | '/'
    | '/api/demo-names'
    | '/api/demo-tq-todos'
    | '/demo/clerk'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/account/$accountId/$applicationId'
    | '/account/$accountId/settings'
    | '/account/$accountId/create'
    | '/account/$accountId/sandbox'
    | '/demo/form/address'
    | '/demo/sentry/testing'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/account/$accountId/$applicationId/insights'
    | '/account/$accountId/$applicationId/keys'
    | '/account/$accountId/$applicationId/logs'
    | '/account/$accountId/$applicationId/security'
    | '/account/$accountId/$applicationId/services'
    | '/account/$accountId/settings/account'
    | '/account/$accountId/settings/members'
    | '/account/$accountId/settings/notifications'
    | '/account/$accountId/settings/plan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiDemoNamesRoute: typeof ApiDemoNamesRoute
  ApiDemoTqTodosRoute: typeof ApiDemoTqTodosRoute
  DemoClerkRoute: typeof DemoClerkRoute
  DemoTableRoute: typeof DemoTableRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  AccountAccountIdApplicationIdRouteRoute: typeof AccountAccountIdApplicationIdRouteRouteWithChildren
  AccountAccountIdSettingsRouteRoute: typeof AccountAccountIdSettingsRouteRouteWithChildren
  AccountAccountIdCreateRoute: typeof AccountAccountIdCreateRoute
  AccountAccountIdSandboxRoute: typeof AccountAccountIdSandboxRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoSentryTestingRoute: typeof DemoSentryTestingRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/clerk': {
      id: '/demo/clerk'
      path: '/demo/clerk'
      fullPath: '/demo/clerk'
      preLoaderRoute: typeof DemoClerkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/demo-tq-todos': {
      id: '/api/demo-tq-todos'
      path: '/api/demo-tq-todos'
      fullPath: '/api/demo-tq-todos'
      preLoaderRoute: typeof ApiDemoTqTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/demo-names': {
      id: '/api/demo-names'
      path: '/api/demo-names'
      fullPath: '/api/demo-names'
      preLoaderRoute: typeof ApiDemoNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/sentry/testing': {
      id: '/demo/sentry/testing'
      path: '/demo/sentry/testing'
      fullPath: '/demo/sentry/testing'
      preLoaderRoute: typeof DemoSentryTestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/$accountId/sandbox': {
      id: '/account/$accountId/sandbox'
      path: '/account/$accountId/sandbox'
      fullPath: '/account/$accountId/sandbox'
      preLoaderRoute: typeof AccountAccountIdSandboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/$accountId/create': {
      id: '/account/$accountId/create'
      path: '/account/$accountId/create'
      fullPath: '/account/$accountId/create'
      preLoaderRoute: typeof AccountAccountIdCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/$accountId/settings': {
      id: '/account/$accountId/settings'
      path: '/account/$accountId/settings'
      fullPath: '/account/$accountId/settings'
      preLoaderRoute: typeof AccountAccountIdSettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/$accountId/$applicationId': {
      id: '/account/$accountId/$applicationId'
      path: '/account/$accountId/$applicationId'
      fullPath: '/account/$accountId/$applicationId'
      preLoaderRoute: typeof AccountAccountIdApplicationIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/$accountId/settings/plan': {
      id: '/account/$accountId/settings/plan'
      path: '/plan'
      fullPath: '/account/$accountId/settings/plan'
      preLoaderRoute: typeof AccountAccountIdSettingsPlanRouteImport
      parentRoute: typeof AccountAccountIdSettingsRouteRoute
    }
    '/account/$accountId/settings/notifications': {
      id: '/account/$accountId/settings/notifications'
      path: '/notifications'
      fullPath: '/account/$accountId/settings/notifications'
      preLoaderRoute: typeof AccountAccountIdSettingsNotificationsRouteImport
      parentRoute: typeof AccountAccountIdSettingsRouteRoute
    }
    '/account/$accountId/settings/members': {
      id: '/account/$accountId/settings/members'
      path: '/members'
      fullPath: '/account/$accountId/settings/members'
      preLoaderRoute: typeof AccountAccountIdSettingsMembersRouteImport
      parentRoute: typeof AccountAccountIdSettingsRouteRoute
    }
    '/account/$accountId/settings/account': {
      id: '/account/$accountId/settings/account'
      path: '/account'
      fullPath: '/account/$accountId/settings/account'
      preLoaderRoute: typeof AccountAccountIdSettingsAccountRouteImport
      parentRoute: typeof AccountAccountIdSettingsRouteRoute
    }
    '/account/$accountId/$applicationId/services': {
      id: '/account/$accountId/$applicationId/services'
      path: '/services'
      fullPath: '/account/$accountId/$applicationId/services'
      preLoaderRoute: typeof AccountAccountIdApplicationIdServicesRouteImport
      parentRoute: typeof AccountAccountIdApplicationIdRouteRoute
    }
    '/account/$accountId/$applicationId/security': {
      id: '/account/$accountId/$applicationId/security'
      path: '/security'
      fullPath: '/account/$accountId/$applicationId/security'
      preLoaderRoute: typeof AccountAccountIdApplicationIdSecurityRouteImport
      parentRoute: typeof AccountAccountIdApplicationIdRouteRoute
    }
    '/account/$accountId/$applicationId/logs': {
      id: '/account/$accountId/$applicationId/logs'
      path: '/logs'
      fullPath: '/account/$accountId/$applicationId/logs'
      preLoaderRoute: typeof AccountAccountIdApplicationIdLogsRouteImport
      parentRoute: typeof AccountAccountIdApplicationIdRouteRoute
    }
    '/account/$accountId/$applicationId/keys': {
      id: '/account/$accountId/$applicationId/keys'
      path: '/keys'
      fullPath: '/account/$accountId/$applicationId/keys'
      preLoaderRoute: typeof AccountAccountIdApplicationIdKeysRouteImport
      parentRoute: typeof AccountAccountIdApplicationIdRouteRoute
    }
    '/account/$accountId/$applicationId/insights': {
      id: '/account/$accountId/$applicationId/insights'
      path: '/insights'
      fullPath: '/account/$accountId/$applicationId/insights'
      preLoaderRoute: typeof AccountAccountIdApplicationIdInsightsRouteImport
      parentRoute: typeof AccountAccountIdApplicationIdRouteRoute
    }
  }
}

interface AccountAccountIdApplicationIdRouteRouteChildren {
  AccountAccountIdApplicationIdInsightsRoute: typeof AccountAccountIdApplicationIdInsightsRoute
  AccountAccountIdApplicationIdKeysRoute: typeof AccountAccountIdApplicationIdKeysRoute
  AccountAccountIdApplicationIdLogsRoute: typeof AccountAccountIdApplicationIdLogsRoute
  AccountAccountIdApplicationIdSecurityRoute: typeof AccountAccountIdApplicationIdSecurityRoute
  AccountAccountIdApplicationIdServicesRoute: typeof AccountAccountIdApplicationIdServicesRoute
}

const AccountAccountIdApplicationIdRouteRouteChildren: AccountAccountIdApplicationIdRouteRouteChildren =
  {
    AccountAccountIdApplicationIdInsightsRoute:
      AccountAccountIdApplicationIdInsightsRoute,
    AccountAccountIdApplicationIdKeysRoute:
      AccountAccountIdApplicationIdKeysRoute,
    AccountAccountIdApplicationIdLogsRoute:
      AccountAccountIdApplicationIdLogsRoute,
    AccountAccountIdApplicationIdSecurityRoute:
      AccountAccountIdApplicationIdSecurityRoute,
    AccountAccountIdApplicationIdServicesRoute:
      AccountAccountIdApplicationIdServicesRoute,
  }

const AccountAccountIdApplicationIdRouteRouteWithChildren =
  AccountAccountIdApplicationIdRouteRoute._addFileChildren(
    AccountAccountIdApplicationIdRouteRouteChildren,
  )

interface AccountAccountIdSettingsRouteRouteChildren {
  AccountAccountIdSettingsAccountRoute: typeof AccountAccountIdSettingsAccountRoute
  AccountAccountIdSettingsMembersRoute: typeof AccountAccountIdSettingsMembersRoute
  AccountAccountIdSettingsNotificationsRoute: typeof AccountAccountIdSettingsNotificationsRoute
  AccountAccountIdSettingsPlanRoute: typeof AccountAccountIdSettingsPlanRoute
}

const AccountAccountIdSettingsRouteRouteChildren: AccountAccountIdSettingsRouteRouteChildren =
  {
    AccountAccountIdSettingsAccountRoute: AccountAccountIdSettingsAccountRoute,
    AccountAccountIdSettingsMembersRoute: AccountAccountIdSettingsMembersRoute,
    AccountAccountIdSettingsNotificationsRoute:
      AccountAccountIdSettingsNotificationsRoute,
    AccountAccountIdSettingsPlanRoute: AccountAccountIdSettingsPlanRoute,
  }

const AccountAccountIdSettingsRouteRouteWithChildren =
  AccountAccountIdSettingsRouteRoute._addFileChildren(
    AccountAccountIdSettingsRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiDemoNamesRoute: ApiDemoNamesRoute,
  ApiDemoTqTodosRoute: ApiDemoTqTodosRoute,
  DemoClerkRoute: DemoClerkRoute,
  DemoTableRoute: DemoTableRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  AccountAccountIdApplicationIdRouteRoute:
    AccountAccountIdApplicationIdRouteRouteWithChildren,
  AccountAccountIdSettingsRouteRoute:
    AccountAccountIdSettingsRouteRouteWithChildren,
  AccountAccountIdCreateRoute: AccountAccountIdCreateRoute,
  AccountAccountIdSandboxRoute: AccountAccountIdSandboxRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoSentryTestingRoute: DemoSentryTestingRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
