/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo.tanstack-query'
import { Route as DemoTableRouteImport } from './routes/demo.table'
import { Route as DemoClerkRouteImport } from './routes/demo.clerk'
import { Route as ApiDemoTqTodosRouteImport } from './routes/api.demo-tq-todos'
import { Route as ApiDemoNamesRouteImport } from './routes/api.demo-names'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo.start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo.start.api-request'
import { Route as DemoSentryTestingRouteImport } from './routes/demo.sentry.testing'
import { Route as DemoFormAddressRouteImport } from './routes/demo.form.address'
import { Route as AuthedAccountAccountIdRouteRouteImport } from './routes/_authed/account.$accountId/route'
import { Route as AuthedAccountAccountIdSandboxRouteImport } from './routes/_authed/account.$accountId/sandbox'
import { Route as AuthedAccountAccountIdCreateRouteImport } from './routes/_authed/account.$accountId/create'
import { Route as AuthedAccountAccountIdSettingsRouteRouteImport } from './routes/_authed/account.$accountId/settings/route'
import { Route as AuthedAccountAccountIdApplicationIdRouteRouteImport } from './routes/_authed/account.$accountId/$applicationId/route'
import { Route as AuthedAccountAccountIdSettingsPlanRouteImport } from './routes/_authed/account.$accountId/settings/plan'
import { Route as AuthedAccountAccountIdSettingsNotificationsRouteImport } from './routes/_authed/account.$accountId/settings/notifications'
import { Route as AuthedAccountAccountIdSettingsMembersRouteImport } from './routes/_authed/account.$accountId/settings/members'
import { Route as AuthedAccountAccountIdSettingsAccountRouteImport } from './routes/_authed/account.$accountId/settings/account'
import { Route as AuthedAccountAccountIdApplicationIdServicesRouteImport } from './routes/_authed/account.$accountId/$applicationId/services'
import { Route as AuthedAccountAccountIdApplicationIdSecurityRouteImport } from './routes/_authed/account.$accountId/$applicationId/security'
import { Route as AuthedAccountAccountIdApplicationIdLogsRouteImport } from './routes/_authed/account.$accountId/$applicationId/logs'
import { Route as AuthedAccountAccountIdApplicationIdKeysRouteImport } from './routes/_authed/account.$accountId/$applicationId/keys'
import { Route as AuthedAccountAccountIdApplicationIdInsightsRouteImport } from './routes/_authed/account.$accountId/$applicationId/insights'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoClerkRoute = DemoClerkRouteImport.update({
  id: '/demo/clerk',
  path: '/demo/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDemoTqTodosRoute = ApiDemoTqTodosRouteImport.update({
  id: '/api/demo-tq-todos',
  path: '/api/demo-tq-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDemoNamesRoute = ApiDemoNamesRouteImport.update({
  id: '/api/demo-names',
  path: '/api/demo-names',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoSentryTestingRoute = DemoSentryTestingRouteImport.update({
  id: '/demo/sentry/testing',
  path: '/demo/sentry/testing',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAccountAccountIdRouteRoute =
  AuthedAccountAccountIdRouteRouteImport.update({
    id: '/account/$accountId',
    path: '/account/$accountId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedAccountAccountIdSandboxRoute =
  AuthedAccountAccountIdSandboxRouteImport.update({
    id: '/sandbox',
    path: '/sandbox',
    getParentRoute: () => AuthedAccountAccountIdRouteRoute,
  } as any)
const AuthedAccountAccountIdCreateRoute =
  AuthedAccountAccountIdCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthedAccountAccountIdRouteRoute,
  } as any)
const AuthedAccountAccountIdSettingsRouteRoute =
  AuthedAccountAccountIdSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthedAccountAccountIdRouteRoute,
  } as any)
const AuthedAccountAccountIdApplicationIdRouteRoute =
  AuthedAccountAccountIdApplicationIdRouteRouteImport.update({
    id: '/$applicationId',
    path: '/$applicationId',
    getParentRoute: () => AuthedAccountAccountIdRouteRoute,
  } as any)
const AuthedAccountAccountIdSettingsPlanRoute =
  AuthedAccountAccountIdSettingsPlanRouteImport.update({
    id: '/plan',
    path: '/plan',
    getParentRoute: () => AuthedAccountAccountIdSettingsRouteRoute,
  } as any)
const AuthedAccountAccountIdSettingsNotificationsRoute =
  AuthedAccountAccountIdSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthedAccountAccountIdSettingsRouteRoute,
  } as any)
const AuthedAccountAccountIdSettingsMembersRoute =
  AuthedAccountAccountIdSettingsMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthedAccountAccountIdSettingsRouteRoute,
  } as any)
const AuthedAccountAccountIdSettingsAccountRoute =
  AuthedAccountAccountIdSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthedAccountAccountIdSettingsRouteRoute,
  } as any)
const AuthedAccountAccountIdApplicationIdServicesRoute =
  AuthedAccountAccountIdApplicationIdServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthedAccountAccountIdApplicationIdRouteRoute,
  } as any)
const AuthedAccountAccountIdApplicationIdSecurityRoute =
  AuthedAccountAccountIdApplicationIdSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthedAccountAccountIdApplicationIdRouteRoute,
  } as any)
const AuthedAccountAccountIdApplicationIdLogsRoute =
  AuthedAccountAccountIdApplicationIdLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => AuthedAccountAccountIdApplicationIdRouteRoute,
  } as any)
const AuthedAccountAccountIdApplicationIdKeysRoute =
  AuthedAccountAccountIdApplicationIdKeysRouteImport.update({
    id: '/keys',
    path: '/keys',
    getParentRoute: () => AuthedAccountAccountIdApplicationIdRouteRoute,
  } as any)
const AuthedAccountAccountIdApplicationIdInsightsRoute =
  AuthedAccountAccountIdApplicationIdInsightsRouteImport.update({
    id: '/insights',
    path: '/insights',
    getParentRoute: () => AuthedAccountAccountIdApplicationIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/demo-names': typeof ApiDemoNamesRoute
  '/api/demo-tq-todos': typeof ApiDemoTqTodosRoute
  '/demo/clerk': typeof DemoClerkRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/account/$accountId': typeof AuthedAccountAccountIdRouteRouteWithChildren
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/sentry/testing': typeof DemoSentryTestingRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/account/$accountId/$applicationId': typeof AuthedAccountAccountIdApplicationIdRouteRouteWithChildren
  '/account/$accountId/settings': typeof AuthedAccountAccountIdSettingsRouteRouteWithChildren
  '/account/$accountId/create': typeof AuthedAccountAccountIdCreateRoute
  '/account/$accountId/sandbox': typeof AuthedAccountAccountIdSandboxRoute
  '/account/$accountId/$applicationId/insights': typeof AuthedAccountAccountIdApplicationIdInsightsRoute
  '/account/$accountId/$applicationId/keys': typeof AuthedAccountAccountIdApplicationIdKeysRoute
  '/account/$accountId/$applicationId/logs': typeof AuthedAccountAccountIdApplicationIdLogsRoute
  '/account/$accountId/$applicationId/security': typeof AuthedAccountAccountIdApplicationIdSecurityRoute
  '/account/$accountId/$applicationId/services': typeof AuthedAccountAccountIdApplicationIdServicesRoute
  '/account/$accountId/settings/account': typeof AuthedAccountAccountIdSettingsAccountRoute
  '/account/$accountId/settings/members': typeof AuthedAccountAccountIdSettingsMembersRoute
  '/account/$accountId/settings/notifications': typeof AuthedAccountAccountIdSettingsNotificationsRoute
  '/account/$accountId/settings/plan': typeof AuthedAccountAccountIdSettingsPlanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/demo-names': typeof ApiDemoNamesRoute
  '/api/demo-tq-todos': typeof ApiDemoTqTodosRoute
  '/demo/clerk': typeof DemoClerkRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/account/$accountId': typeof AuthedAccountAccountIdRouteRouteWithChildren
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/sentry/testing': typeof DemoSentryTestingRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/account/$accountId/$applicationId': typeof AuthedAccountAccountIdApplicationIdRouteRouteWithChildren
  '/account/$accountId/settings': typeof AuthedAccountAccountIdSettingsRouteRouteWithChildren
  '/account/$accountId/create': typeof AuthedAccountAccountIdCreateRoute
  '/account/$accountId/sandbox': typeof AuthedAccountAccountIdSandboxRoute
  '/account/$accountId/$applicationId/insights': typeof AuthedAccountAccountIdApplicationIdInsightsRoute
  '/account/$accountId/$applicationId/keys': typeof AuthedAccountAccountIdApplicationIdKeysRoute
  '/account/$accountId/$applicationId/logs': typeof AuthedAccountAccountIdApplicationIdLogsRoute
  '/account/$accountId/$applicationId/security': typeof AuthedAccountAccountIdApplicationIdSecurityRoute
  '/account/$accountId/$applicationId/services': typeof AuthedAccountAccountIdApplicationIdServicesRoute
  '/account/$accountId/settings/account': typeof AuthedAccountAccountIdSettingsAccountRoute
  '/account/$accountId/settings/members': typeof AuthedAccountAccountIdSettingsMembersRoute
  '/account/$accountId/settings/notifications': typeof AuthedAccountAccountIdSettingsNotificationsRoute
  '/account/$accountId/settings/plan': typeof AuthedAccountAccountIdSettingsPlanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/api/demo-names': typeof ApiDemoNamesRoute
  '/api/demo-tq-todos': typeof ApiDemoTqTodosRoute
  '/demo/clerk': typeof DemoClerkRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/_authed/account/$accountId': typeof AuthedAccountAccountIdRouteRouteWithChildren
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/sentry/testing': typeof DemoSentryTestingRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/_authed/account/$accountId/$applicationId': typeof AuthedAccountAccountIdApplicationIdRouteRouteWithChildren
  '/_authed/account/$accountId/settings': typeof AuthedAccountAccountIdSettingsRouteRouteWithChildren
  '/_authed/account/$accountId/create': typeof AuthedAccountAccountIdCreateRoute
  '/_authed/account/$accountId/sandbox': typeof AuthedAccountAccountIdSandboxRoute
  '/_authed/account/$accountId/$applicationId/insights': typeof AuthedAccountAccountIdApplicationIdInsightsRoute
  '/_authed/account/$accountId/$applicationId/keys': typeof AuthedAccountAccountIdApplicationIdKeysRoute
  '/_authed/account/$accountId/$applicationId/logs': typeof AuthedAccountAccountIdApplicationIdLogsRoute
  '/_authed/account/$accountId/$applicationId/security': typeof AuthedAccountAccountIdApplicationIdSecurityRoute
  '/_authed/account/$accountId/$applicationId/services': typeof AuthedAccountAccountIdApplicationIdServicesRoute
  '/_authed/account/$accountId/settings/account': typeof AuthedAccountAccountIdSettingsAccountRoute
  '/_authed/account/$accountId/settings/members': typeof AuthedAccountAccountIdSettingsMembersRoute
  '/_authed/account/$accountId/settings/notifications': typeof AuthedAccountAccountIdSettingsNotificationsRoute
  '/_authed/account/$accountId/settings/plan': typeof AuthedAccountAccountIdSettingsPlanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/demo-names'
    | '/api/demo-tq-todos'
    | '/demo/clerk'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/account/$accountId'
    | '/demo/form/address'
    | '/demo/sentry/testing'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/account/$accountId/$applicationId'
    | '/account/$accountId/settings'
    | '/account/$accountId/create'
    | '/account/$accountId/sandbox'
    | '/account/$accountId/$applicationId/insights'
    | '/account/$accountId/$applicationId/keys'
    | '/account/$accountId/$applicationId/logs'
    | '/account/$accountId/$applicationId/security'
    | '/account/$accountId/$applicationId/services'
    | '/account/$accountId/settings/account'
    | '/account/$accountId/settings/members'
    | '/account/$accountId/settings/notifications'
    | '/account/$accountId/settings/plan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/demo-names'
    | '/api/demo-tq-todos'
    | '/demo/clerk'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/account/$accountId'
    | '/demo/form/address'
    | '/demo/sentry/testing'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/account/$accountId/$applicationId'
    | '/account/$accountId/settings'
    | '/account/$accountId/create'
    | '/account/$accountId/sandbox'
    | '/account/$accountId/$applicationId/insights'
    | '/account/$accountId/$applicationId/keys'
    | '/account/$accountId/$applicationId/logs'
    | '/account/$accountId/$applicationId/security'
    | '/account/$accountId/$applicationId/services'
    | '/account/$accountId/settings/account'
    | '/account/$accountId/settings/members'
    | '/account/$accountId/settings/notifications'
    | '/account/$accountId/settings/plan'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/api/demo-names'
    | '/api/demo-tq-todos'
    | '/demo/clerk'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/_authed/account/$accountId'
    | '/demo/form/address'
    | '/demo/sentry/testing'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/_authed/account/$accountId/$applicationId'
    | '/_authed/account/$accountId/settings'
    | '/_authed/account/$accountId/create'
    | '/_authed/account/$accountId/sandbox'
    | '/_authed/account/$accountId/$applicationId/insights'
    | '/_authed/account/$accountId/$applicationId/keys'
    | '/_authed/account/$accountId/$applicationId/logs'
    | '/_authed/account/$accountId/$applicationId/security'
    | '/_authed/account/$accountId/$applicationId/services'
    | '/_authed/account/$accountId/settings/account'
    | '/_authed/account/$accountId/settings/members'
    | '/_authed/account/$accountId/settings/notifications'
    | '/_authed/account/$accountId/settings/plan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  ApiDemoNamesRoute: typeof ApiDemoNamesRoute
  ApiDemoTqTodosRoute: typeof ApiDemoTqTodosRoute
  DemoClerkRoute: typeof DemoClerkRoute
  DemoTableRoute: typeof DemoTableRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoSentryTestingRoute: typeof DemoSentryTestingRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/clerk': {
      id: '/demo/clerk'
      path: '/demo/clerk'
      fullPath: '/demo/clerk'
      preLoaderRoute: typeof DemoClerkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/demo-tq-todos': {
      id: '/api/demo-tq-todos'
      path: '/api/demo-tq-todos'
      fullPath: '/api/demo-tq-todos'
      preLoaderRoute: typeof ApiDemoTqTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/demo-names': {
      id: '/api/demo-names'
      path: '/api/demo-names'
      fullPath: '/api/demo-names'
      preLoaderRoute: typeof ApiDemoNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/sentry/testing': {
      id: '/demo/sentry/testing'
      path: '/demo/sentry/testing'
      fullPath: '/demo/sentry/testing'
      preLoaderRoute: typeof DemoSentryTestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/account/$accountId': {
      id: '/_authed/account/$accountId'
      path: '/account/$accountId'
      fullPath: '/account/$accountId'
      preLoaderRoute: typeof AuthedAccountAccountIdRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/account/$accountId/sandbox': {
      id: '/_authed/account/$accountId/sandbox'
      path: '/sandbox'
      fullPath: '/account/$accountId/sandbox'
      preLoaderRoute: typeof AuthedAccountAccountIdSandboxRouteImport
      parentRoute: typeof AuthedAccountAccountIdRouteRoute
    }
    '/_authed/account/$accountId/create': {
      id: '/_authed/account/$accountId/create'
      path: '/create'
      fullPath: '/account/$accountId/create'
      preLoaderRoute: typeof AuthedAccountAccountIdCreateRouteImport
      parentRoute: typeof AuthedAccountAccountIdRouteRoute
    }
    '/_authed/account/$accountId/settings': {
      id: '/_authed/account/$accountId/settings'
      path: '/settings'
      fullPath: '/account/$accountId/settings'
      preLoaderRoute: typeof AuthedAccountAccountIdSettingsRouteRouteImport
      parentRoute: typeof AuthedAccountAccountIdRouteRoute
    }
    '/_authed/account/$accountId/$applicationId': {
      id: '/_authed/account/$accountId/$applicationId'
      path: '/$applicationId'
      fullPath: '/account/$accountId/$applicationId'
      preLoaderRoute: typeof AuthedAccountAccountIdApplicationIdRouteRouteImport
      parentRoute: typeof AuthedAccountAccountIdRouteRoute
    }
    '/_authed/account/$accountId/settings/plan': {
      id: '/_authed/account/$accountId/settings/plan'
      path: '/plan'
      fullPath: '/account/$accountId/settings/plan'
      preLoaderRoute: typeof AuthedAccountAccountIdSettingsPlanRouteImport
      parentRoute: typeof AuthedAccountAccountIdSettingsRouteRoute
    }
    '/_authed/account/$accountId/settings/notifications': {
      id: '/_authed/account/$accountId/settings/notifications'
      path: '/notifications'
      fullPath: '/account/$accountId/settings/notifications'
      preLoaderRoute: typeof AuthedAccountAccountIdSettingsNotificationsRouteImport
      parentRoute: typeof AuthedAccountAccountIdSettingsRouteRoute
    }
    '/_authed/account/$accountId/settings/members': {
      id: '/_authed/account/$accountId/settings/members'
      path: '/members'
      fullPath: '/account/$accountId/settings/members'
      preLoaderRoute: typeof AuthedAccountAccountIdSettingsMembersRouteImport
      parentRoute: typeof AuthedAccountAccountIdSettingsRouteRoute
    }
    '/_authed/account/$accountId/settings/account': {
      id: '/_authed/account/$accountId/settings/account'
      path: '/account'
      fullPath: '/account/$accountId/settings/account'
      preLoaderRoute: typeof AuthedAccountAccountIdSettingsAccountRouteImport
      parentRoute: typeof AuthedAccountAccountIdSettingsRouteRoute
    }
    '/_authed/account/$accountId/$applicationId/services': {
      id: '/_authed/account/$accountId/$applicationId/services'
      path: '/services'
      fullPath: '/account/$accountId/$applicationId/services'
      preLoaderRoute: typeof AuthedAccountAccountIdApplicationIdServicesRouteImport
      parentRoute: typeof AuthedAccountAccountIdApplicationIdRouteRoute
    }
    '/_authed/account/$accountId/$applicationId/security': {
      id: '/_authed/account/$accountId/$applicationId/security'
      path: '/security'
      fullPath: '/account/$accountId/$applicationId/security'
      preLoaderRoute: typeof AuthedAccountAccountIdApplicationIdSecurityRouteImport
      parentRoute: typeof AuthedAccountAccountIdApplicationIdRouteRoute
    }
    '/_authed/account/$accountId/$applicationId/logs': {
      id: '/_authed/account/$accountId/$applicationId/logs'
      path: '/logs'
      fullPath: '/account/$accountId/$applicationId/logs'
      preLoaderRoute: typeof AuthedAccountAccountIdApplicationIdLogsRouteImport
      parentRoute: typeof AuthedAccountAccountIdApplicationIdRouteRoute
    }
    '/_authed/account/$accountId/$applicationId/keys': {
      id: '/_authed/account/$accountId/$applicationId/keys'
      path: '/keys'
      fullPath: '/account/$accountId/$applicationId/keys'
      preLoaderRoute: typeof AuthedAccountAccountIdApplicationIdKeysRouteImport
      parentRoute: typeof AuthedAccountAccountIdApplicationIdRouteRoute
    }
    '/_authed/account/$accountId/$applicationId/insights': {
      id: '/_authed/account/$accountId/$applicationId/insights'
      path: '/insights'
      fullPath: '/account/$accountId/$applicationId/insights'
      preLoaderRoute: typeof AuthedAccountAccountIdApplicationIdInsightsRouteImport
      parentRoute: typeof AuthedAccountAccountIdApplicationIdRouteRoute
    }
  }
}

interface AuthedAccountAccountIdApplicationIdRouteRouteChildren {
  AuthedAccountAccountIdApplicationIdInsightsRoute: typeof AuthedAccountAccountIdApplicationIdInsightsRoute
  AuthedAccountAccountIdApplicationIdKeysRoute: typeof AuthedAccountAccountIdApplicationIdKeysRoute
  AuthedAccountAccountIdApplicationIdLogsRoute: typeof AuthedAccountAccountIdApplicationIdLogsRoute
  AuthedAccountAccountIdApplicationIdSecurityRoute: typeof AuthedAccountAccountIdApplicationIdSecurityRoute
  AuthedAccountAccountIdApplicationIdServicesRoute: typeof AuthedAccountAccountIdApplicationIdServicesRoute
}

const AuthedAccountAccountIdApplicationIdRouteRouteChildren: AuthedAccountAccountIdApplicationIdRouteRouteChildren =
  {
    AuthedAccountAccountIdApplicationIdInsightsRoute:
      AuthedAccountAccountIdApplicationIdInsightsRoute,
    AuthedAccountAccountIdApplicationIdKeysRoute:
      AuthedAccountAccountIdApplicationIdKeysRoute,
    AuthedAccountAccountIdApplicationIdLogsRoute:
      AuthedAccountAccountIdApplicationIdLogsRoute,
    AuthedAccountAccountIdApplicationIdSecurityRoute:
      AuthedAccountAccountIdApplicationIdSecurityRoute,
    AuthedAccountAccountIdApplicationIdServicesRoute:
      AuthedAccountAccountIdApplicationIdServicesRoute,
  }

const AuthedAccountAccountIdApplicationIdRouteRouteWithChildren =
  AuthedAccountAccountIdApplicationIdRouteRoute._addFileChildren(
    AuthedAccountAccountIdApplicationIdRouteRouteChildren,
  )

interface AuthedAccountAccountIdSettingsRouteRouteChildren {
  AuthedAccountAccountIdSettingsAccountRoute: typeof AuthedAccountAccountIdSettingsAccountRoute
  AuthedAccountAccountIdSettingsMembersRoute: typeof AuthedAccountAccountIdSettingsMembersRoute
  AuthedAccountAccountIdSettingsNotificationsRoute: typeof AuthedAccountAccountIdSettingsNotificationsRoute
  AuthedAccountAccountIdSettingsPlanRoute: typeof AuthedAccountAccountIdSettingsPlanRoute
}

const AuthedAccountAccountIdSettingsRouteRouteChildren: AuthedAccountAccountIdSettingsRouteRouteChildren =
  {
    AuthedAccountAccountIdSettingsAccountRoute:
      AuthedAccountAccountIdSettingsAccountRoute,
    AuthedAccountAccountIdSettingsMembersRoute:
      AuthedAccountAccountIdSettingsMembersRoute,
    AuthedAccountAccountIdSettingsNotificationsRoute:
      AuthedAccountAccountIdSettingsNotificationsRoute,
    AuthedAccountAccountIdSettingsPlanRoute:
      AuthedAccountAccountIdSettingsPlanRoute,
  }

const AuthedAccountAccountIdSettingsRouteRouteWithChildren =
  AuthedAccountAccountIdSettingsRouteRoute._addFileChildren(
    AuthedAccountAccountIdSettingsRouteRouteChildren,
  )

interface AuthedAccountAccountIdRouteRouteChildren {
  AuthedAccountAccountIdApplicationIdRouteRoute: typeof AuthedAccountAccountIdApplicationIdRouteRouteWithChildren
  AuthedAccountAccountIdSettingsRouteRoute: typeof AuthedAccountAccountIdSettingsRouteRouteWithChildren
  AuthedAccountAccountIdCreateRoute: typeof AuthedAccountAccountIdCreateRoute
  AuthedAccountAccountIdSandboxRoute: typeof AuthedAccountAccountIdSandboxRoute
}

const AuthedAccountAccountIdRouteRouteChildren: AuthedAccountAccountIdRouteRouteChildren =
  {
    AuthedAccountAccountIdApplicationIdRouteRoute:
      AuthedAccountAccountIdApplicationIdRouteRouteWithChildren,
    AuthedAccountAccountIdSettingsRouteRoute:
      AuthedAccountAccountIdSettingsRouteRouteWithChildren,
    AuthedAccountAccountIdCreateRoute: AuthedAccountAccountIdCreateRoute,
    AuthedAccountAccountIdSandboxRoute: AuthedAccountAccountIdSandboxRoute,
  }

const AuthedAccountAccountIdRouteRouteWithChildren =
  AuthedAccountAccountIdRouteRoute._addFileChildren(
    AuthedAccountAccountIdRouteRouteChildren,
  )

interface AuthedRouteChildren {
  AuthedAccountAccountIdRouteRoute: typeof AuthedAccountAccountIdRouteRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAccountAccountIdRouteRoute:
    AuthedAccountAccountIdRouteRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  ApiDemoNamesRoute: ApiDemoNamesRoute,
  ApiDemoTqTodosRoute: ApiDemoTqTodosRoute,
  DemoClerkRoute: DemoClerkRoute,
  DemoTableRoute: DemoTableRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoSentryTestingRoute: DemoSentryTestingRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
